package com.booktrain_crawl.dto;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class SeatDTO {
    private Integer id;
    private String seatNumber;
    private Integer compartmentNo;
    private String berthPosition;
    private Integer carriageId;
    private Integer carriageOrder;
    private String carriageType;
    private Boolean isVip;
    private String status;    // "available" | "booked"
    private Long price;       // VND đầy đủ

    // Grid position from Vexere API 2 (null if generated by fallback)
    private Integer gridRow;
    private Integer gridCol;
    private String seatCode;   // "1", "B1" (table), null for generated seats
    private String loaiCho;    // "NML", "NMLV", null for generated seats
}
